export const NEWS_REQUEST = 'NEWS_REQUEST';
export const APOD_REQUEST = 'APOD_REQUEST';
export const ASTEROID_REQUEST = 'ASTEROID_REQUEST';
export const EARTH_IMAGERY_REQUEST = 'EARTH_IMAGERY_REQUEST';
